name: Keep App Awake

on:
  schedule:

    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I -L -A "Mozilla/5.0" https://pdf-ai-chatbot-ay2we7dxosyp7klbjs5u4x.streamlit.app